package provider

import (
	"context"
	"fmt"
	"github.com/hashicorp/terraform-plugin-framework/resource"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/planmodifier"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/stringplanmodifier"
	"github.com/hashicorp/terraform-plugin-framework/types"
)

var (
	_ resource.Resource = &createvmResource{}
)

type createvmResource struct{}

type createvmResourceModel struct {
	UUID   types.String `tfsdk:"uuid"`
	Name   types.String `tfsdk:"name"`
	Cpus   types.Int32  `tfsdk:"cpus"`
	Memory types.Int64  `tfsdk:"memory"`
}

func (r *createvmResource) Metadata(ctx context.Context, request resource.MetadataRequest, response *resource.MetadataResponse) {
	response.TypeName = request.ProviderTypeName + "_createvm"
}

func (r *createvmResource) Schema(ctx context.Context, request resource.SchemaRequest, response *resource.SchemaResponse) {
	response.Schema = schema.Schema{
		Description: "Create a new Virtual Machine using and register the VM with your Oracle VM VirtualBox installation.",
		Attributes: map[string]schema.Attribute{
			"uuid": schema.StringAttribute{
				Description: "The UUID of the Virtual Machine. This is generated by VirtualBox when the VM is created.",
				Computed:    true,
				PlanModifiers: []planmodifier.String{
					stringplanmodifier.UseStateForUnknown(),
				},
			},
			"name": schema.StringAttribute{
				Description: "The name of the Virtual Machine to create.",
				Required:    true,
			},
			"cpus": schema.Int32Attribute{
				Required:    true,
				Description: "The number of virtual CPUs to assign to the Virtual Machine.",
			},
			"memory": schema.Int64Attribute{
				Required:    true,
				Description: "The amount of memory (in MB) to assign to the Virtual Machine.",
			},
		},
	}
}

func (r *createvmResource) Create(ctx context.Context, request resource.CreateRequest, response *resource.CreateResponse) {
	// Retrieve values from plan
	var plan createvmResourceModel
	diags := request.Plan.Get(ctx, &plan)
	response.Diagnostics.Append(diags...)
	if response.Diagnostics.HasError() {
		return
	}

	vmName := plan.Name.ValueString()
	vmMemory := plan.Memory.ValueInt64()
	vmCpus := plan.Cpus.ValueInt32()

	// 1. Create VM
	if err := RunVBoxManage("createvm", "--name", vmName, "--register"); err != nil {
		response.Diagnostics.AddError(
			"Error creating VM",
			"Could not create virtual machine, unexpected error: "+err.Error(),
		)
		return
	}

	// 2. Modify VM settings
	if err := RunVBoxManage("modifyvm", vmName, "--memory", fmt.Sprintf("%d", vmMemory), "--cpus", fmt.Sprintf("%d", vmCpus)); err != nil {
		response.Diagnostics.AddError(
			"Error modifying VM",
			"Could not modify virtual machine, unexpected error: "+err.Error(),
		)
		return
	}

	// Map response body to schema and populate Computed attribute values
	output, err := RunVBoxManageWithOutput("showvminfo", vmName, "--machinereadable")
	if err != nil {
		response.Diagnostics.AddError(
			"Error reading VM",
			"Could not read virtual machine information, unexpected error: "+err.Error(),
		)
		return
	}

	// Parse the output to get the UUID and other details
	vmInfo := ParseShowVMInfo(output)

	plan.UUID = types.StringValue(GetVMInfoFromOutput(vmInfo, "UUID"))

	// Set state to fully populated data
	diags = response.State.Set(ctx, plan)
	response.Diagnostics.Append(diags...)
	if response.Diagnostics.HasError() {
		return
	}
}

func (r *createvmResource) Read(ctx context.Context, request resource.ReadRequest, response *resource.ReadResponse) {
	// Get current state
	var state createvmResourceModel
	diags := request.State.Get(ctx, &state)
	response.Diagnostics.Append(diags...)
	if response.Diagnostics.HasError() {
		return
	}

	vmName := state.Name.ValueString()

	output, err := RunVBoxManageWithOutput("showvminfo", vmName, "--machinereadable")
	if err != nil {
		response.Diagnostics.AddError(
			"Error reading VM",
			"Could not read virtual machine information, unexpected error: "+err.Error(),
		)
		return
	}

	// Parse the output to get the UUID and other details
	vmInfo := ParseShowVMInfo(output)

	// Overwrite uuid with refreshed state
	state.UUID = types.StringValue(GetVMInfoFromOutput(vmInfo, "UUID"))

	// Set refreshed state
	diags = response.State.Set(ctx, &state)
	response.Diagnostics.Append(diags...)
	if response.Diagnostics.HasError() {
		return
	}
}

func (r *createvmResource) Update(ctx context.Context, request resource.UpdateRequest, response *resource.UpdateResponse) {
}

func (r *createvmResource) Delete(ctx context.Context, request resource.DeleteRequest, response *resource.DeleteResponse) {
}

func NewCreateVmResource() resource.Resource {
	return &createvmResource{}
}
